from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse
import pandas as pd

from src.utils.config import EXPORTS_DIR


router = APIRouter()


@router.get("/dashboard", response_class=HTMLResponse, include_in_schema=False)
def action_plan_dashboard() -> str:
    """
    Simple HTML dashboard for recruiters:
    - Reads action_plan.csv from data/exports/
    - Shows a summary and top-N high-risk users with planned interventions.
    """
    path = EXPORTS_DIR / "action_plan.csv"
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=f"Action plan not found at {path}. Run: make pipeline",
        )

    df = pd.read_csv(path)
    total_users = len(df)
    n_actionable = (df["final_action"] != "no_action").sum()
    top = df.sort_values("churn_prob", ascending=False).head(200)

    # Build a minimal, clean HTML table
    table_html = top.to_html(
        classes="table table-striped",
        index=False,
        float_format=lambda x: f"{x:0.3f}" if isinstance(x, float) else x,
    )

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Churn Action Plan Dashboard</title>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
        <style>
            body {{
                padding: 2rem;
                background-color: #0f172a;
                color: #e5e7eb;
            }}
            h1, h2 {{
                color: #f9fafb;
            }}
            .metric-card {{
                background: #020617;
                border-radius: 0.75rem;
                padding: 1rem 1.25rem;
                border: 1px solid #1f2937;
            }}
            .table-container {{
                margin-top: 1.5rem;
                background: #020617;
                border-radius: 0.75rem;
                padding: 1rem;
                border: 1px solid #1f2937;
                overflow-x: auto;
            }}
            table {{
                color: #e5e7eb !important;
            }}
            thead th {{
                background-color: #020617 !important;
            }}
            tbody tr:nth-child(even) {{
                background-color: #020617 !important;
            }}
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <h1 class="mb-3">Churn Action Plan</h1>
            <p class="text-muted mb-4">
                Snapshot of high-risk users and their recommended interventions,
                generated by the full pipeline.
            </p>

            <div class="row g-3 mb-3">
                <div class="col-md-4">
                    <div class="metric-card">
                        <div class="text-sm text-muted">High-risk users</div>
                        <div class="h4 mb-0">{total_users:,}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="metric-card">
                        <div class="text-sm text-muted">Users with intervention</div>
                        <div class="h4 mb-0">{n_actionable:,}</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="metric-card">
                        <div class="text-sm text-muted">Intervention rate</div>
                        <div class="h4 mb-0">
                            {(n_actionable / total_users * 100):.1f}%
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-container">
                <h2 class="h5 mb-3">Top {len(top):,} high-risk users</h2>
                {table_html}
            </div>
        </div>
    </body>
    </html>
    """
    return html
