-- =============================================================================
-- feat_master.sql
-- Joins all feature tables into one wide feature table.
--
-- Also joins:
--   - change_points.csv (loaded separately after PELT detection)
--   - stg_feature_events (SaaS feature adoption features)
--   - stg_interventions (email engagement features)
--   - Ground truth labels from raw_train
--
-- This is the single source of truth for the ML layer.
-- All downstream models and marts read from feat_master.
-- =============================================================================

-- First: load change_points.csv if it exists
-- (Generated by src/features/change_point_detection.py)
CREATE OR REPLACE TABLE raw_change_points AS
SELECT * FROM read_csv_auto('data/exports/change_points.csv', ignore_errors=true);


-- ── SaaS Feature Adoption Features ───────────────────────────────────────────
-- Derived directly from stg_feature_events
CREATE OR REPLACE TABLE feat_feature_adoption AS

WITH ref AS (
    SELECT DATE '2017-03-31' AS ref_date
),

enriched AS (
    SELECT
        fe.*,
        DATE_DIFF('day', fe.event_date, r.ref_date) AS days_ago
    FROM stg_feature_events fe
    CROSS JOIN ref r
)

SELECT
    msno,

    -- Feature breadth: how many distinct features used
    COUNT(DISTINCT CASE
        WHEN days_ago <= 30 THEN feature_name END)       AS unique_features_used_30d,
    COUNT(DISTINCT feature_name)                         AS unique_features_used_all,

    -- Feature diversity score: ratio of features used to total available (10)
    ROUND(COUNT(DISTINCT CASE
        WHEN days_ago <= 30 THEN feature_name END) / 10.0, 4) AS feature_diversity_score,

    -- Recency of last feature interaction
    MIN(CASE WHEN days_ago >= 0 THEN days_ago END)       AS days_since_last_feature_use,

    -- Session depth
    AVG(CASE WHEN days_ago <= 30
        THEN session_duration_sec END)                   AS avg_session_duration_30d,

    SUM(CASE WHEN days_ago <= 30
        THEN session_duration_sec ELSE 0 END)            AS total_session_sec_30d

FROM enriched
GROUP BY msno;


-- ── Intervention Engagement Features ─────────────────────────────────────────
CREATE OR REPLACE TABLE feat_intervention_engagement AS

SELECT
    msno,
    intervention_type                                    AS last_intervention_type,
    email_opened,
    email_clicked

FROM stg_interventions;


-- ── MASTER FEATURE TABLE ──────────────────────────────────────────────────────
CREATE OR REPLACE TABLE feat_master AS

SELECT
    -- Identity
    m.msno,

    -- Labels
    t.is_churn,

    -- ── Member features ──────────────────────────────────────────────────────
    m.gender_male_flag,
    m.city,
    m.registered_via,
    m.age,
    m.age_bucket,
    m.tenure_days,

    -- ── Usage decay ──────────────────────────────────────────────────────────
    COALESCE(ud.sessions_last_30d, 0)          AS sessions_last_30d,
    COALESCE(ud.sessions_last_60d, 0)          AS sessions_last_60d,
    COALESCE(ud.sessions_last_90d, 0)          AS sessions_last_90d,
    COALESCE(ud.hours_last_30d, 0)             AS hours_last_30d,
    COALESCE(ud.avg_daily_hours_last_30d, 0)   AS avg_session_duration_30d,
    ud.usage_decay_30d,
    ud.usage_decay_60d,
    ud.usage_decay_90d,
    COALESCE(ud.completion_rate_avg_30d, 0)    AS completion_rate_avg_30d,
    COALESCE(ud.skip_rate_avg_30d, 0)          AS skip_rate_avg_30d,

    -- ── Login frequency ───────────────────────────────────────────────────────
    COALESCE(lf.login_days_last_30d, 0)        AS login_days_last_30d,
    COALESCE(lf.login_days_last_60d, 0)        AS login_days_last_60d,
    COALESCE(lf.login_gap_days_avg, 0)         AS login_gap_days_avg,
    COALESCE(lf.login_gap_days_max, 0)         AS login_gap_days_max,
    COALESCE(lf.login_gap_days_recent, 0)      AS login_gap_days_recent,
    COALESCE(lf.login_streak_max, 0)           AS login_streak_max,
    COALESCE(lf.login_streak_current, 0)       AS login_streak_current,
    COALESCE(lf.days_since_last_login, 999)    AS days_since_last_login,

    -- ── Support signals ───────────────────────────────────────────────────────
    COALESCE(ss.ticket_count_30d, 0)           AS ticket_count_30d,
    COALESCE(ss.ticket_count_90d, 0)           AS ticket_count_90d,
    COALESCE(ss.ticket_velocity, 0)            AS ticket_velocity,
    COALESCE(ss.pct_negative_sentiment, 0)     AS pct_negative_sentiment,
    COALESCE(ss.unresolved_ticket_count, 0)    AS unresolved_ticket_count,
    COALESCE(ss.has_cancellation_inquiry, 0)   AS has_cancellation_inquiry,
    COALESCE(ss.cancellation_inquiry_30d, 0)   AS cancellation_inquiry_30d,
    COALESCE(ss.billing_ticket_count, 0)       AS billing_ticket_count,

    -- ── Transaction signals ───────────────────────────────────────────────────
    COALESCE(tx.auto_renew_flag, 0)            AS auto_renew_flag,
    COALESCE(tx.is_cancel_flag, 0)             AS is_cancel_flag,
    COALESCE(tx.plan_downgrade_flag, 0)        AS plan_downgrade_flag,
    COALESCE(tx.payment_failure_count_90d, 0)  AS payment_failure_count_90d,
    COALESCE(tx.days_since_last_txn, 999)      AS days_since_last_txn,
    COALESCE(tx.membership_expire_days, 0)     AS membership_expire_days,
    COALESCE(tx.avg_discount_rate, 0)          AS avg_discount_rate,
    COALESCE(tx.payment_method_changes, 1)     AS payment_method_changes,
    COALESCE(tx.total_paid_90d, 0)             AS total_paid_90d,
    COALESCE(tx.cancellation_count, 0)         AS cancellation_count,

    -- ── Feature adoption (synthetic) ──────────────────────────────────────────
    COALESCE(fa.unique_features_used_30d, 0)   AS unique_features_used_30d,
    COALESCE(fa.feature_diversity_score, 0)    AS feature_diversity_score,
    COALESCE(fa.days_since_last_feature_use, 999) AS days_since_last_feature_use,

    -- ── Change points (from PELT) ─────────────────────────────────────────────
    COALESCE(cp.change_point_detected, false)  AS change_point_detected,
    cp.change_point_date,
    COALESCE(cp.days_since_change_point, 999)  AS days_since_change_point,
    COALESCE(cp.usage_slope_post_change, 0)    AS usage_slope_post_change,
    COALESCE(cp.pct_usage_change, 0)           AS pct_usage_change,

    -- ── Intervention engagement ───────────────────────────────────────────────
    ie.last_intervention_type,
    COALESCE(ie.email_opened,  false)          AS email_opened,
    COALESCE(ie.email_clicked, false)          AS email_clicked

FROM stg_members m

-- Labels (inner join: only labelled users)
INNER JOIN raw_train t ON m.msno = t.msno

-- Feature joins (all LEFT: users may have no activity in some tables)
LEFT JOIN feat_usage_decay           ud ON m.msno = ud.msno
LEFT JOIN feat_login_frequency       lf ON m.msno = lf.msno
LEFT JOIN feat_support_signals       ss ON m.msno = ss.msno
LEFT JOIN feat_transaction_signals   tx ON m.msno = tx.msno
LEFT JOIN feat_feature_adoption      fa ON m.msno = fa.msno
LEFT JOIN raw_change_points          cp ON m.msno = cp.msno
LEFT JOIN feat_intervention_engagement ie ON m.msno = ie.msno;
